version: '1'
services:
  backend:
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command:  > 
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver  0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=password
      - SECRET_KEY= 
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASS=password
      - DATABASE_HOST=db
      - EMAIL_HOST_USER=hello@gmail.com
      - EMAIL_HOST_PASSWORD=demo_password

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: postgres  
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

