
version: '1'

services:
  app:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: codecommunitymusic-backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: codecommunitymusic-db
    environment:
      - POSTGRES_DB=codeforcommunity
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kushwaha
    volumes:
      - .:/dbdata
    ports:
      - "5432:5432"
    depends_on:
      - cache
  cache:
    image: redis:latest
    container_name: codecommunitymusic-cache
    ports:
      - "6379:6379"