version: '1'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command:  > 
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver  0.0.0.0:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: password
    networks:
      - codecommunitymusic-network

  db:
    image: postgres:16  
    environment:
      POSTGRES_DB: name  
      POSTGRES_USER: root  
      POSTGRES_PASSWORD: password  
    networks:
      - codecommunitymusic-network

networks:
  codecommunitymusic-network:
