# Generated by Django 4.0 on 2023-06-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
